routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\MemberController;

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/members', 'MemberController');
Route::resource('/authors', 'AuthorController');
Route::resource('/books', 'BookController');
Route::resource('/loans', 'LoanController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = ['author_id','title'];

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = ucwords($value);
    }

    public function copy()
    {
        return $this->hasOne(Copy::class,'book_id','id');
    }
    public function author()
    {
        return $this->belongsTo(Author::class);
    }

}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use App\Book;
use App\Copy;
use App\Http\Requests\UpdateBookRequest;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::get();
        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $authors = Author::all()->pluck('first_name','id');
        return view('books.create', compact('authors'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $book = new Book;
        $book->title = $request->title;
        $book->author_id = $request->authors[0];
        $book->save();

        $copies =  new Copy;
        $copies->available =  $request->available;
        $copies->total =  $request->total;
        $copies->book()->associate($book);
        $copies->save();


        return redirect()->route('books.index')->with('success', "Libro creado con éxito.");

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {

        $authors = Author::all()->pluck('first_name','id');
        return view('books.edit', compact('book','authors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookRequest $request, Book $book)
    {

        $book->update([
            'title' => $request->title,
            'author_id' => $request->authors
        ]);

        $copy = Copy::where('book_id',$book->id);
        $copy->update([
            'available' => $request->available,
            'total' => $request->total
        ]);

        return redirect()->route('books.index')->with('success', "Libro actualizado con éxito.");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->copy()->delete();
        $book->delete();
    }
}

resources/views/books/create.blade.php
@extends('adminlte::page')

@section('title', 'Libros')

@section('content')

    {!! Form::open(['route' => 'books.store', 'method'=>'post','class' => 'col-sm-12']) !!}

    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Nuevo Libro</h3>
                    <br>

                    @include('books.partials.form')

                    <div class="row">
                        <div class="col-sm-12">
                            <a href="{{ route('books.index') }}" type="button" class="btn btn-danger float-left">
                                <span class="fa fa-arrow-left"></span>&emsp;
                                Volver
                            </a>

                            <button type="submit" class="btn btn-primary float-right">
                                Guardar&emsp;
                                <span class="fa fa-save"></span>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

@endsection

resources/views/books/edit.blade.php
@extends('adminlte::page')

@section('title', 'Socios')

@section('content')

{{--    {!! Form::model($store,['route' => ['stores.update',$store], 'method'=>'put','class' => 'col-sm-12']) !!}--}}

    {!! Form::model($book,['route' => ['books.update',$book], 'method'=>'put','class' => 'col-sm-12']) !!}

    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Editar Libro : {{$book->title}}</h3>
                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @include('books.partials.form')


                    <div class="row">
                        <div class="col-sm-12">
                            <a href="{{ route('books.index') }}" type="button" class="btn btn-danger float-left">
                                <span class="fa fa-arrow-left"></span>&emsp;
                                Volver
                            </a>

                            <button type="submit" class="btn btn-primary float-right">
                                Guardar&emsp;
                                <span class="fa fa-save"></span>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {!! Form::close() !!}

@endsection

resources/views/books/index.blade.php
@extends('adminlte::page')

@section('title', 'Libros')
@section('content')
    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Libros</h3>
                </div>
                @include('partials.alerts')
                <div class="table-responsive">
                    <table id="users" class="table table-hover table-striped center">
                        <thead>
                        <tr class="text-center">
                            <th class="text-center">Id</th>
                            <th class="text-center">Titulo</th>
                            <th class="text-center">Autor</th>
                            <th class="text-center">Total de Copias</th>
                            <th class="text-center">Total Disponibles</th>
                            <th class="text-center">Acción</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($books as $book)
                            <tr>
                                <td class="text-center">{{ $book->id }}</td>
                                <td class="text-center">{{ $book->title }}</td>
                                <td class="text-center">{{ $book->author->last_name }}, {{ $book->author->first_name }}</td>
                                <td class="text-center">{{ $book->copy->total }}</td>
                                <td class="text-center">{{ $book->copy->available }}</td>
                                <td class="text-center">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{ route('books.edit',['member'=>$book->id]) }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="left" title="Editar">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="{{ route('books.show',['member'=>$book->id]) }}" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Ver">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <button class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="right" title="Eliminar" onclick="deleteBook({{$book->id}},'{{$book->title}}')">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>


                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('js')

    <script type="text/javascript">


        $(function () {
            $('[data-toggle="tooltip"]').tooltip()

            $('.select2').select2();

        })

        function deleteBook(userId,userName){
            Swal.fire({
                title: '¿Estas seguro que deseas Eliminar el socio: '+userName+ '?',
                text: "¡No podrás reverir este cambio!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, eliminar!',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {

                    $.ajax({

                        url: 'books/'+userId,
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function (result) {
                            Swal.fire(
                                'Eliminado!',
                                'El Usuario fue eliminado!',
                                'success'
                            ).then((result) => {
                                if (result.isConfirmed) {
                                    window.location.reload();
                                }
                            })

                        }
                    });

                }
            })
        }

    </script>
@endsection