routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\MemberController;

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/members', 'MemberController');
Route::resource('/authors', 'AuthorController');
Route::resource('/books', 'BookController');
Route::resource('/loans', 'LoanController');

app/Loan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    protected $fillable = ['id','book_id','member_id','status','observations'];



    public function setStatusAttribute($value)
    {
        $this->attributes['status'] = ucwords($value);
    }

    public function setObservationsttribute($value)
    {
        $this->attributes['observations'] = ucwords($value);
    }
    public function books()
    {
        return $this->hasOne(Book::class,'id','book_id');
    }

    public function member()
    {
        return $this->belongsTo(Member::class);
    }
}

app/Http/Controllers/LoanController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Copy;
use App\Loan;
use App\Member;
use Illuminate\Http\Request;

class LoanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $loans = Loan::get();
        return view('loans.index',compact('loans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $members = Member::where('active', 1)
            ->where('book_limit', '>', 0)
            ->get()
            ->map(function ($member) {
                return [
                    'full_name' => $member->first_name . ' ' . $member->last_name,
                    'id' => $member->id
                ];
            })
            ->pluck('full_name', 'id');

        $books = Book::whereHas('copy', function ($query) {
            $query->where('available', '>', 0);
        })
            ->get()
            ->pluck('title', 'id');

        $status = [
            'En proceso' => 'En proceso',
            'Entregado' => 'Entregado'
        ];

        return view('loans.create', compact('members', 'books', 'status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Loan::create([
            'book_id' => $request->books,
            'member_id' => $request->member,
            'status' => $request->status,
            'observations' => $request->observations,
        ]);

        if ($request->status == 'En proceso') {

            $copy = Copy::where('book_id', $request->books)->first();
            $sumAvailable = $copy->available - 1;

            $copy->where('book_id', $request->books)
                ->update([
                    'available' => $sumAvailable
                ]);
        }

        return redirect()->route('loans.index')->with('success', "Préstamo creado con éxito.");

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function show(Loan $loan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Loan $loan)
    {
        $members = Member::where('active', 1)
            ->where('book_limit', '>', 0)
            ->get()
            ->map(function ($member) {
                return [
                    'full_name' => $member->first_name . ' ' . $member->last_name,
                    'id' => $member->id
                ];
            })
            ->pluck('full_name', 'id');

        $books = Book::whereHas('copy', function ($query) {
            $query->where('available', '>', 0);
        })
            ->get()
            ->pluck('title','id');

        $status = [
            'En proceso' => 'En proceso',
            'Entregado' => 'Entregado'
        ];
        return view('loans.edit',compact('members','books','status','loan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Loan $loan)
    {
        $loan->update([
            'book_id' => $request->books,
            'member_id' => $request->member,
            'status' => $request->status,
            'observations' => $request->observations,
        ]);

        if ($request->status == 'Entregado') {

            $copy = Copy::where('book_id', $request->books)->first();
            $sumAvailable = $copy->available + 1;

            $copy->where('book_id', $request->books)
            ->update([
                'available' => $sumAvailable
            ]);
        }

        return redirect()->route('loans.index')->with('success', "Préstamo editado con éxito.");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Loan $loan)
    {
        //
    }
}

resources/views/loans/create.blade.php
@extends('adminlte::page')

@section('title', 'Prestamo')

@section('content')

    {!! Form::open(['route' => 'loans.store', 'method'=>'post','class' => 'col-sm-12']) !!}

    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Nuevo Préstamo</h3>
                    <br>

                    @include('loans.partials.form')

                    <div class="row">
                        <div class="col-sm-12">
                            <a href="{{ route('loans.index') }}" type="button" class="btn btn-danger float-left">
                                <span class="fa fa-arrow-left"></span>&emsp;
                                Volver
                            </a>

                            <button type="submit" class="btn btn-primary float-right">
                                Guardar&emsp;
                                <span class="fa fa-save"></span>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

@endsection

resources/views/loans/edit.blade.php
@extends('adminlte::page')

@section('title', 'Prestamo')

@section('content')


    {!! Form::model($loan,['route' => ['loans.update',$loan], 'method'=>'put','class' => 'col-sm-12']) !!}

    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Editar Préstamos</h3>

                    @include('loans.partials.form')


                    <div class="row">
                        <div class="col-sm-12">
                            <a href="{{ route('loans.index') }}" type="button" class="btn btn-danger float-left">
                                <span class="fa fa-arrow-left"></span>&emsp;
                                Volver
                            </a>

                            <button type="submit" class="btn btn-primary float-right">
                                Guardar&emsp;
                                <span class="fa fa-save"></span>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {!! Form::close() !!}

@endsection

resources/views/loans/index.blade.php
@extends('adminlte::page')

@section('title', 'Prestamos')
@section('content')
    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Préstamos</h3>
                </div>
                @include('partials.alerts')
                <div class="table-responsive">
                    <table id="users" class="table table-hover table-striped center">
                        <thead>
                        <tr class="text-center">
                            <th class="text-center">Id</th>
                            <th class="text-center">Socio</th>
                            <th class="text-center">Libro</th>
                            <th class="text-center">Estado</th>
                            <th class="text-center">Observaciones</th>
                            <th class="text-center">Acción</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($loans as $loan)
                            <tr>
                                <td class="text-center">{{ $loan->id }}</td>
                                <td class="text-center">{{ $loan->member->first_name }}, {{ $loan->member->last_name }}</td>
                                <td class="text-center">{{ $loan->books->title }}</td>
                                <td class="text-center">
                                    @if($loan->status == 'En Proceso' )
                                        <span class="badge btn-warning"> {{ $loan->status }} </span>
                                    @endif

                                    @if($loan->status == 'Entregado' )
                                            <span class="badge btn-success">{{$loan->status}}</span>
                                        @endif
                                </td>
                                <td class="text-center">{{ $loan->observations}}</td>
                                <td class="text-center">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{ route('loans.edit',['member'=>$loan->id]) }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="left" title="Editar">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="{{ route('loans.show',['member'=>$loan->id]) }}" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Ver">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('js')

    <script type="text/javascript">


        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })


    </script>
@endsection