routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\MemberController;

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/members', 'MemberController');
Route::resource('/authors', 'AuthorController');
Route::resource('/books', 'BookController');
Route::resource('/loans', 'LoanController');

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $fillable = ['first_name','last_name','phone','book_limit','active'];
    protected $appends = ['full_name'];
    public function setFirstNameAttribute($value)
    {
        $this->attributes['first_name'] = ucwords($value);
    }

    public function setLastNameAttribute($value)
    {
        $this->attributes['last_name'] = ucwords($value);
    }
    public function getFullNameAttribute()
    {
        return $this->attributes['first_name'] . ' ' . $this->attributes['last_name'];
    }
    public function loans()
    {
        return $this->belongsToMany(Book::class, 'loans', 'member_id', 'book_id')->withTimestamps();
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreMemberRequest;
use App\Http\Requests\UpdateMemberRequest;
use App\Member;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $members = Member::all();
        return view('members.index',compact('members'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('members.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMemberRequest $request)
    {

        Member::create($request->validated());

        return redirect()->route('members.index')->with('success', "Socio creado con éxito.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function show(Member $member)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Member $member)
    {
        return view('members.edit', compact('member'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateMemberRequest $request, Member $member)
    {

        $member->update($request->validated());

        return redirect()->route('members.index')->with('success', "Socio actualizada con éxito.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function destroy(Member $member)
    {
        $member->delete();

    }
}

resources/views/members/create.blade.php
@extends('adminlte::page')

@section('title', 'Socios')

@section('content')

    {!! Form::open(['route' => 'members.store', 'method'=>'post','class' => 'col-sm-12']) !!}

    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Nuevo Socio</h3>
                    <br>

                    @include('members.partials.form')

                    <div class="row">
                        <div class="col-sm-12">
                            <a href="{{ route('members.index') }}" type="button" class="btn btn-danger float-left">
                                <span class="fa fa-arrow-left"></span>&emsp;
                                Volver
                            </a>

                            <button type="submit" class="btn btn-primary float-right">
                                Guardar&emsp;
                                <span class="fa fa-save"></span>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

@endsection

resources/views/members/edit.blade.php
@extends('adminlte::page')

@section('title', 'Socios')

@section('content')

{{--    {!! Form::model($store,['route' => ['stores.update',$store], 'method'=>'put','class' => 'col-sm-12']) !!}--}}

    {!! Form::model($member,['route' => ['members.update',$member], 'method'=>'put','class' => 'col-sm-12']) !!}

    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Editar Socio : {{$member->first_name}}</h3>

                    @include('members.partials.form')


                    <div class="row">
                        <div class="col-sm-12">
                            <a href="{{ route('members.index') }}" type="button" class="btn btn-danger float-left">
                                <span class="fa fa-arrow-left"></span>&emsp;
                                Volver
                            </a>

                            <button type="submit" class="btn btn-primary float-right">
                                Guardar&emsp;
                                <span class="fa fa-save"></span>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {!! Form::close() !!}

@endsection

resources/views/members/index.blade.php
@extends('adminlte::page')

@section('title', 'Socios')
@section('content')
    <div class="row">
        <div class="mt-3 col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="font-weight-bold">Socios</h3>
                </div>
                @include('partials.alerts')
                <div class="table-responsive">
                    <table id="users" class="table table-hover table-striped center">
                        <thead>
                        <tr class="text-center">
                            <th class="text-center">Id</th>
                            <th class="text-center">Nombre</th>
                            <th class="text-center">Apellido</th>
                            <th class="text-center">Telefono</th>
                            <th class="text-center">Estado</th>
                            <th class="text-center">Limite de libros</th>
                            <th class="text-center">Acción</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($members as $member)
                            <tr>
                                <td class="text-center">{{ $member->id }}</td>
                                <td class="text-center">{{ $member->first_name }}</td>
                                <td class="text-center">{{ $member->last_name }}</td>
                                <td class="text-center">{{ $member->phone }}</td>
                                <td class="text-center">
                                    @if($member->active == 1 )
                                        <span class="badge btn-success">Activo</span>
                                    @endif

                                    @if($member->active == 0 )
                                            <span class="badge btn-danger">Inactivo</span>
                                        @endif
                                </td>
                                <td class="text-center">{{ $member->book_limit }}</td>
                                <td class="text-center">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{ route('members.edit',['member'=>$member->id]) }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="left" title="Editar">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="{{ route('members.show',['member'=>$member->id]) }}" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Ver">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <button class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="right" title="Eliminar" onclick="deleteMember({{$member->id}},'{{$member->first_name}}')">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>


                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('js')

    <script type="text/javascript">


        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })

        function deleteMember(userId,userName){
            Swal.fire({
                title: '¿Estas seguro que deseas Eliminar el socio: '+userName+ '?',
                text: "¡No podrás reverir este cambio!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, eliminar!',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                console.log(result)
                if (result.isConfirmed) {

                    $.ajax({

                        url: 'members/'+userId,
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function (result) {
                            Swal.fire(
                                'Eliminado!',
                                'El Usuario fue eliminado!',
                                'success'
                            ).then((result) => {
                                if (result.isConfirmed) {
                                    window.location.reload();
                                }
                            })

                        }
                    });

                }
            })
        }

    </script>
@endsection